# Generated by Django 4.0.3 on 2022-03-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='image',
            field=models.ImageField(default=1, upload_to='build/static/'),
            preserve_default=False,
        ),
    ]
